### PR TITLE
Added Leona

### PR DESCRIPTION
**Pull request by Zarthbenn**
Added Leona abilities/tooltips/icons/hero. 

Its important to note that there are some minor issues that I could not fix. (not really gamebreaking)
- When using Zenith Blade on a group of units very close together, Leona and targets could get stuck (rooted) permanently.
- Passive should not be able to be triggered by Leona. When OnAttacked is triggered the caster is always referenced as Leona so I could not create an if statement to check if caster is not her.
- Zenith Blade should go in this order: Cast, Projectile launched, Projectile went full distance and ended, Leona get re-positioned to where farthest target is, End. Currently the re-positioning is done as the projectile travels. This is probably due to the nature of the pudge hook script that I used. As far as I could find there is no timberchain or clockwerk hook datadriven (or similar) code that I can refrence.

Il open an issue with above when this gets pulled.

### CODE REVIEW

**Comment by wfzyx** [comment]
I'm looking for providing a custom game to we devs test this stuffs in game, i'll merge this and start the bug tracking as soon i get this working.

at the moment, reborn broke something in the howling abyss map, so i'll looking forward to fix the map first.

for the moment, nice work :+1:

**Comment by Capruce** [comment]
K i'm currently working on an update that'll be ready soon, it's pretty
much a finished Lux, a system for handling AP, levelup stats + early
kassadin and a rudimentary custom projectile manager for things like
boomerang projectiles that some champions use e.g. Lux, Draven, Gnar, Ekko
etc

**Comment by wfzyx** [comment]
The "boomerang" mechanic, is actually a 2 projectile skill, with A->B, B->(A or C or Hero)  points. We can make a interface for this for sure.

**Comment by Capruce** [comment]
I know but the problem is Dota 2 doesn't support tracking projectiles that
hit units other than the target. So I'm creating a custom tracking
projectile unit.

**Comment by wfzyx** [comment]
You are actually wrong !

Look at [this](https://github.com/coldAmphibian/Defense-of-the-Legends/blob/master/game/dota_addons/dotl/scripts/vscripts/heroes/hero_ezreal/ezreal_arcane_shift.lua#L23-L36) code.

You can set any valid unit as a target, if you need a fixed point on the map, you can crate a invisible unit dynamically with Lua, and use them as target

**Comment by Capruce** [comment]
No no I mean the tracking projectile won't proc an event for passing
through or hitting other units other than its target (as opposed to a
linear projectile) which is a problem for nearly every 'boomerang' spell
since they all use it

**Comment by Zarthbenn** [comment]
Alright great! Good to see development is still underway. Personally im still having issues coming up with a solution to bubbles/sheilds (sonas w aura, blitzcranks passive, and obviously other champs bubbles) other than that sona is 75% done.

**Comment by wfzyx** [comment]
@Capruce This can be done with a entity following the tracking projectile using lua detection, the same concept I explained before.

@Zarthbenn You're having trouble putting a shield on units? You can use [Apotic shield code](https://github.com/Pizzalol/SpellLibrary/blob/SpellLibrary/game/dota_addons/spelllibrary/scripts/vscripts/heroes/hero_abaddon/aphotic_shield.lua) on Spell Library as a good reference. If you have any trouble get in touch with me. I'm wFX on irc

**Comment by Zarthbenn** [comment]
@vhpanisa oh wow thanks, I couldn't find something like this when I was searching.

**Comment by wfzyx** [comment]
@Capruce There is [a function](https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Scripting/API/CDOTA_Ability_Lua.OnProjectileThink) which gives the current vector position of a projectile when it moves, AND there is a [another one](https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Scripting/API/CDOTA_Ability_Lua.OnProjectileThink_ExtraData) which handles extra data in a table.

I didn't test, but i'm pretty sure with this we can make something reasonable, in which trigger of think you can make a "GetUnitsCloseWhatever", and check if they are inside of colision radius, and do stuff. This removes the need of a invisible entity being dragged around i think

**Comment by Capruce** [comment]
Yeah I'm in the process of testing them. First I tried to see if
OnProjectileThink could be a DD block but no luck. Now making an ability to
test it with tracking projectiles

**Comment by wfzyx** [comment]
Idk if this matters, but me, for instance, don't use DD abilities unless strictly necessary, (which never happens). Because lua gives far more room to bug fixes, and workarounds.

Also it can be tested with script_reload far more easilly

**Comment by Capruce** [comment]
...script_reload has no affect on lua abilities...

**Comment by wfzyx** [comment]
It have, test

**Comment by Capruce** [comment]
I have, many times, neither script_reload or script_reload_code seem to have any affect for me. If you know a specific way that works, it would help a lot.

**Comment by wfzyx** [comment]
You need to specify the file with the .lua extension.

E.g:

script_reload ezreal_rising_spell_force.lua

**Comment by coldAmphibian** [comment]
Something else to consider is that in LoL, a champion fires their skillshot regardless of whether you targetted outside of its range or not whereas in Dota, you walk up to reachable range before casting.

**Comment by Zarthbenn** [comment]
gonna fix some additional stuff for leona and add sona while im at it. We should have a public forum or something to discuss things like above

**Comment by wn-mitch** [comment]
I have a website I could host a forum on if you give me a software package to install. We would need a host name for it.

**Comment by wn-mitch** [comment]
I also have the subreddit /r/defenseofthelegends

**Comment by wfzyx** [comment]
I think the subreddit can get the work done, right @coldAmphibian ?

**Comment by coldAmphibian** [comment]
sure

**Comment by coldAmphibian** [comment]
i guess you can make that post in this subreddit XD

**Pull request closed without merging**
