### PR TITLE
Added an early basic way to work with stats from LoL + more champions

### PR DESCRIPTION
**Pull request by Capruce**
Reworked Lux abilities
Added Kassadin, Veigar and an early Karthus

Added an early system to be able to remove the Dota attributes of a hero and work with the LoL Stats.
Look at my champions to see how it works or feel free to suggest a different implementation.

Once again I suck with at GitHub somehow so please be sure to explain everything I've done wrong T_T

### CODE REVIEW

**Comment by wfzyx** [comment]
I didn't read line by line, but i got the concept, and looks good for me, maybe it causes some problems with targeting, but i'm not sure.

Also your commit just made me realize we should make separated commits of assets / gamecode, to ease our read

**Comment by Capruce** [comment]
Good point! (Like I said I suck at git) Want me to go back and split up the commits?

**Comment by wn-mitch** [comment]
I think it would be easier. I'm trying to find a way to get our commits to autopost to the subreddit

**Comment by wfzyx** [comment]
I'm trying to merge this for a couple for hours now, and i just can't

**Comment by Capruce** [comment]
Dw I'm not in a position where I can work on it but tomorrow I will split it up and make it more readable slash mergable. Sorry for making such a large commit

**Comment by wfzyx** [comment]
i just posted on the wrong pr, i actually was meaning the PR#10 T.T

**Comment by wfzyx** [comment]
#29 closes this?

**Pull request closed without merging**
