### PR TITLE
Added Veigar + fixed Mundo Sadism (had an extra " in it)

### PR DESCRIPTION
**Pull request by Capruce**
I swear I tell it to commit to coldAmphibian/master and it commits to my own one.....

### CODE REVIEW

**Comment by wfzyx** [comment]
Do you use git shell or github for windows? (fancy UI)

**Comment by Capruce** [comment]
GitHub for windows. It clearly stated I'll be committing to
coldAmphibian/master though.....

**Comment by wfzyx** [comment]
I'd suggest to remove your local folder, and ask for ghub to make a new coldAm/Dotl clone. Ghub for windows is buggy sometimes

**Comment by wn-mitch** [comment]
Thanks for fixing that!

**Pull request merged**
